### ISSUE TITLE
Praying for Bodyguard

### ISSUE THREAD

**Issue by jcoppock** [divad/ActivityMafia#3]
If the Bodyguard guards someone who is attacked, and a Citizen prays for the Bodyguard and it works, the Bodyguard isn't healed.

**Comment by divad** [comment]
It isn't meant to.

**Comment by divad** [comment]
Bodyguards die in place of their target, their health is irrelevant - they take the death instead of another player. For the bodyguard to live the attacked person would have to have been healed instead.
